version: '3.8'

services:
  test-backend:
    build:
      context: ./quant/backend
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - SECRET_KEY=test-secret-key-that-is-long-enough-for-testing
      - DATABASE_URL=postgresql://quant_user:quant_password@postgres:5432/quant_db
      - REDIS_URL=redis://redis:6379/0
      - PROJECT_NAME=Quant Test
      - VERSION=1.0.0
      - API_V1_STR=/api/v1
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - BACKEND_CORS_ORIGINS=["http://localhost:3000","http://localhost:8000"]
    command: >
      sh -c "
        echo '=== Testing Improvements ===' &&
        python -c '
from app.core.config_validator import validate_config_on_startup
from app.core.rate_limit_enhanced import EnhancedRateLimiter
from app.core.audit import AuditLogger
from app.schemas.analytics import EnsemblePredictionResponse
print(\"✅ All imports successful\")
print(\"✅ Config validator loaded\")
print(\"✅ Enhanced rate limiter loaded\")
print(\"✅ Audit logger loaded\")
print(\"✅ OpenAPI schemas loaded\")
        ' &&
        echo '=== Starting Server ===' &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - quant-network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=quant_user
      - POSTGRES_PASSWORD=quant_password
      - POSTGRES_DB=quant_db
    networks:
      - quant-network

  redis:
    image: redis:7
    networks:
      - quant-network

networks:
  quant-network:
    driver: bridge